(MainThread) 190618_10:53:14.212 INFO client.py:178 sent startApi
(MainThread) 190618_10:53:14.212 INFO client.py:88 REQUEST startApi {}
(MainThread) 190618_10:53:14.212 INFO client.py:77 SENDING startApi b'\x00\x00\x00\x0871\x002\x000\x00\x00'
(MainThread) 190618_10:53:14.212 INFO wrapper.py:48 ANSWER managedAccounts {'accountsList': 'U8071180'}
(MainThread) 190618_10:53:14.212 INFO wrapper.py:48 ANSWER nextValidId {'orderId': 60}
(MainThread) 190618_10:53:14.332 INFO client.py:196 disconnecting
(Thread-6) 190618_10:53:14.333 ERROR reader.py:52 unhandled exception in EReader thread
Traceback (most recent call last):
  File "e:\IB\ib_source\ib_data_collection\ibapi\reader.py", line 34, in run
    data = self.conn.recvMsg()
  File "e:\IB\ib_source\ib_data_collection\ibapi\connection.py", line 99, in recvMsg
    buf = self._recvAllMsg()
  File "e:\IB\ib_source\ib_data_collection\ibapi\connection.py", line 119, in _recvAllMsg
    buf = self.socket.recv(4096)
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。
(MainThread) 190618_10:53:14.334 INFO wrapper.py:48 ANSWER connectionClosed {}
(MainThread) 190618_10:53:14.338 ERROR main.py:184 END
