(MainThread) 190611_00:18:42.370 INFO main.py:120 STARTING IB...
(MainThread) 190611_00:18:42.380 INFO client.py:178 sent startApi
(MainThread) 190611_00:18:42.381 INFO client.py:88 REQUEST startApi {}
(MainThread) 190611_00:18:42.381 INFO client.py:77 SENDING startApi b'\x00\x00\x00\x0871\x002\x000\x00\x00'
(MainThread) 190611_00:18:42.383 INFO wrapper.py:48 ANSWER managedAccounts {'accountsList': 'U8071180'}
(MainThread) 190611_00:18:42.384 INFO wrapper.py:48 ANSWER nextValidId {'orderId': 60}
(MainThread) 190611_00:18:42.386 INFO client.py:196 disconnecting
(MainThread) 190611_00:18:42.386 INFO wrapper.py:48 ANSWER connectionClosed {}
(Thread-6) 190611_00:18:42.387 ERROR reader.py:52 unhandled exception in EReader thread
Traceback (most recent call last):
  File "E:\IB\ib_source\ibcollecthistory\ibapi\reader.py", line 34, in run
    data = self.conn.recvMsg()
  File "E:\IB\ib_source\ibcollecthistory\ibapi\connection.py", line 99, in recvMsg
    buf = self._recvAllMsg()
  File "E:\IB\ib_source\ibcollecthistory\ibapi\connection.py", line 119, in _recvAllMsg
    buf = self.socket.recv(4096)
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。
(MainThread) 190611_00:18:42.387 ERROR main.py:132 END
